// Add your code here
const fhsdds_0 = img`
    f f f f f f f f f e e e e e e e e e f f f f e f f f f f f e e f e e f f f f f f f f f f c e e e
    f f f c c c f f f f f f f f f f f f f f f f f f f c c f c f f f f f f f f f f f f f f f c e e e
    f c c c c c c c c f f f f f c f f f f f f f f f f f f f f f f f f f f f f f f f f f f f c e e e
    f f c c c c c c c f f f f c c f f f f e f f f c c f f f f f f f f f f f f f f f f f f f c e e e
    f f f c c f c c c f f f f c c f c f e e e f f f f f f f f f f f f f f f f f f f f f f f c e e e
    f f f f c f f c c f f f f c c f e e e e e f f f f e e e e c f f f f f f c f f c f f f f c e e e
    f f f f f c f c c f f f f c c f e e e e e f e e e e e e e e e f f f f f c f f c f f f f e e e e
    f f f f f f c f f c f f f c c e f e e e e e e e e b b b b e e e e e e e f f f f c f f f e e e e
    f f f f f f f c f f f f f f e e e e e e e e e e b b b b b b b b b b e e e c f f c f f f e e e e
    f f f f f f f f c f f f f f e e e e e e e e e b b b b b b b b b b b b e e e f f f c f f e e e e
    f f f f f f f f f f f f f f e e e e e e e e e b b b b b b b b b b b b e e e e f f f f f e e e e
    f f f f f f f e f f f f f c e e e e e e e e b b b b b b b b b b b b b b e e e f f f f f e e e e
    f f f c f f f f f f f f f e e f e e e e e b b b b b b b b b b b b b b b b e e e f f f f e e e e
    f f f f f f f f f f f f f e e e e e e e b b b b b b b b b b b b b b b b e e e e f f f f e e e e
    f f f f f f f f f f e f c e e e e e e e b b b b b b b b b b b b b b b b b e e e f f f c e e e e
    f f f f f f f f f f f f c e e e e e e b e b b b b b b 3 b b b b b b b b b e e e c f e e e e e e
    f f f f f f f f f f f f e e e e e e e e e b b e b b b b b 3 b 3 3 b b b b b e e e f e e e e e e
    f f f f f f f f f f f f e e e e e e e e e b b b b b b b b 3 b b b b b b b b e e e f e e e e e b
    f f f f f f f f f f f f e e e e e e e e b b b b b b b b b b b b b e b e e e e e e f e e e e e e
    f f f f f f f f f f f f e b e e e e e b b b b b b b b b b b b b b b b b b e e e e c e e e e e e
    f f f f f f f f f f f e e b e e e b b e e e e e b b b b b b b b b b b b b e e e e c e e e e e e
    f f f f f f f f f f f e b b e e b b e e e b b b b b b e b b b b b e b b b e e e e c e e e e e e
    f f f f f c c f f f f c b b e e b b b b b b b b b b b e b b b b b e e e e e e e b c e e e e e e
    f f f f f c c f f f f f e b e e b e b b b b b b b b b e b b e b b b b b b e e e b c e e e e e e
    f f f f c f c f e e f e b b e e e b b b b b b b b b b e b b b e b b b b b b b e e c b c c c e e
    f f f f c f c f e e e e b b e e e b b b b b b b b b e e b b b e b b b b b b b e e c b b c c c c
    f f f f c f c f e e e e b b e e e b b b b 3 3 b b e b b b d b e b 3 b b b b b e e c b b c b c b
    f f f f c f c f e e e e b b e e e b b b b b b b b e b b b b b e e b 3 b b b e e b c c b b c c b
    f f f f c f c f e e e e b b e e e b b b b b b b b e b b b b e e b b b b b b e e b c c b b c c c
    f f f f c f c c e e e e b b e b e b b b b b b b b b b b b b b b b b b b b b e e b c c c c c c c
    f f f f c f c e e b e e b b e b b b b b b b b b b b b b b b b b b b b b b b e e b c c c c c c c
    f f f f c f c e e b e c b b b b b b b b e b e b b b b b b b b b b b b b b b e e e c c c c c c c
    f f f f c f c e e b e c b b b b b b b b e b e e b b b b e e e e e e b b b b e e e e e e e e e e
    f f f f c f c e e b e f b b b b b b b b e b e e b b b d d b b e e b b b b b e e e e e e e e e e
    f f f f c f c e b b e f b b b b b b b e b b b e e e e b b b e e e e b b b b b e e e e c c c c c
    f f f f c f c e e b e f c b b b b b b e b b b b b b b b b e e e e e b b b b e b c c c c c c c c
    f f f f f f c e e b c c c b b b b b e c b b b b b b b b b b b e b b e b b b b b c c c c c c c c
    c c c c c c c c c c c c c b b b b b c e e b b b b b b b b b b b b b e b b b b c c c c c c c c c
    c c c c c c c c c c c c c c b b b c c e e b b b b b b b b b b b b b c c b b b c c c c c c c c c
    c c c c c c c c c c c c c c c b c c c c b b b b b b b b b b b b b b b c b b b c c c c c c c c c
    c c c c c c c c c c c c c c c c c c c b b b b b b b b b b b b b b b b c c b c c c c c c c c c c
    c c c c c c c c c c c c c c c e c c b b b b b b b b b b b b b b b b b c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c e e c c b b b b b b b b b b b b d b b b c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c e e c b b b b b b b b b b b d b b b c c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c e b e b b b b b b b b b b b b b b c e c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c e b b e c b b b b b b b b b b b c c e c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c e b b b e b b b b b b b b b b c c e c c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c c b b b b e e b b b b e e e e e e e c c c c c c c c c c c c c c
    c c c c c c c c c c c c c c c c c e b b b b b b b e e e b e e e e c c c c c c c c c c c c c c c
    `;