// Add your code here
const hava64_0 = img`
    d d d d d d d d d d d d d d d d d d d d d d d d d d d d d d b d d d d d d d d d d d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d d d b d d d b d b b d d d d d d d d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d d d d b b b b b b d b d d d d d d d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d d d b b b d b b b b b b d d d d d d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d d b b b b b b b b b b b d d d d d d d d d d d d d 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d b b b b b d b b b d b b b b d d d d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d d b b b b d b b d b b b b b b d b d d d d d d d d d 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d d b b b d d d d b b b b b b b b b b b d d d d d d d d d 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d b b d d d d d d d b b b b b b b b b b b d d d d d d 1 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d d b d d d d d d d d b b b b b b b b b b b d d d d d d d 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d d b d b d d d d d d d d d b b b b b b b b d b b d d d d d 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d b b b d d d d d d d d d d d d b b b b b b b b b b d d d d 1 1 1 1 1 1 1 1
    d d d d d d d d d d d d d d d d d d d d b b b d d d d d d d d d d d d d b b b b b b d b b d d d d 1 d 1 d 1 1 1 1
    d d d d d d d d d d d d d d d d d d b d d b d d d d d d d d d d d d d d d d b b b b b d b d d d d d d d d 1 1 1 d
    d d d d d d d d d d d d d d d d d b d d d b 1 d d 1 d d d d d d d d d d d d d b b b b b b b d d d d d d d d d d d
    d d d d d d d d d d d d d d d d d d d b b d d d d d 1 d d d d d d d d d d d d d b b b b b b d d d d d d 1 d d d d
    d d d d b b b d d d d d d d d d d d d b b d d d d 1 d d d d d d d d d d d d b b d b b b b b d d d d d d d 1 d d 1
    d b d b d b d b d d b b b b d d d b b b b d d d d d d d d d d d d d d d b b b b d b b b b b d d d d d d d d d d d
    d d d d d b d b b b d b b d d d d d b b b d d d d d d d d d d d d d b b b b d d d b b b b b d d d d d d d d d d d
    d b b b b b b b d b b b b d d d d d b b d d d d d d b d d d d d d b b b b b b b b b b b b b d d d d d d d d d d d
    d d b d b d b b b d b d d d d d d b b b d d d b b b b b d d d d d b b b b b b b b b b b b b b d d d d d d d d d d
    d b d b d b b b b b b b b d d b d b b b d d b d d b b b d d d d d d b b b b d b b b b b b b d b b b b b b b d d d
    b d d b d b b d b b b b d d d d d b b b 1 d d d d b b b d d d d d b b b b b b b b b b b b b b b d b b d b b b b b
    b d d b d b b b d b b b d d d d b b b b 1 d d d d d d d d d d d d d d b d b b d d d b b b b b d d d d b d b d d b
    b b b b b b b d b b d d d d b d b b b d 1 d d d d d d d d d d d d d d d d b b d d d b b b b d d b d d d d d d d d
    b b b b b b b b b b b d d d b d b b b d d d d d d d d d d d 1 d d d b d b d d d d d b b b b b b d d d d d b d b d
    b b b b b b b b b b b d d b b b b b b 1 d d 1 d d d d d d d d d d d b d d d d d d d b b b b b d d b d b d d d d d
    b b b b b b b b b b b d b b d b b b b 1 d 1 d d d 1 d d d b b d b b b b d d d d d d b b b b b b b d d d d b d d d
    b d b d d b b b b b d d d b d b b b b d d d d d d d d d d d d d b b b d b d d d d d b b b b b b d d d d d d d d d
    b b d b b b b b b b d d b b d b b b b d d d d d d d d d d d d d d b d b d b d b b d b b b b b b d d d d d d d d d
    b b b b b b b b b b d d b d b b b b b d d d d d d d d d d d d d d d d b b b d b b b b b b b b b b d d d d d d d d
    b b b b b b b b b b b d b b d b b b b b d d d d d d d d d d d d d d b b b b b b b b b b b b b b d b d d d d d d d
    b b b b b b b b b b d d b d d b b b b b d d d d d d d d d b b b b b b b b b b b b b b b b b b b b b b b b b b b d
    d b b b b b b b b d d b b d b b b d b b d d d d d d d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b
    d b b b b b b b b d d b b d b b b d b b b d d d d d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b
    d d b b b b b b d d b b d d b b b b b b b d d d d d d b b b b b b b b b b b b b b b b b b b b b b b b d b b d d b
    b b b d b b b b b d d b d d b b b b b b b b d d d d d d b b b b b b d b b b b b b b b b b b b b b b b d b b b b b
    b b b b b b b b b d b b d d b b b b b b b b d d d d d d d b b b b b b b b b b b b b b b b b b b b b b b d d b b b
    d d b b b b d b b d b b d b b b b d b b b b b d d d d d d d d d b b b b b b b b b b b b b b b b b b b d d b b b b
    d d d b b b d b d d b b d b b b b b b b b b d b d d d d d d b b b b b b b b b b b b b b b b b b b b b d d b b b b
    d d d b b d d b d b b d d b b b b b b b b b d b d d d d d d d d b b b b b b b b b b b b b b b b b b d d d d b b b
    d d d b b b b b d d b d b b b b b b b b b b b d b d d d d d d d b b b b b b b b b b b b b b b b b b b b d b b b b
    d d d b d b b b d b b d b b b b b d b b b b b d d b d d d d d d b b b b b b b b b b b b b b b b b b b b d b b b b
    d d d b b b b b d b b b b b b b b b d b b b b d d d b d d d d b b b b b b b b b b b b b b b b b b d b b b b b b b
    d d d b b b b d d b b d b b b b b d d b b b b b b b b d d d b d b b b b b b b b b b b b b b b b d d d b b b b b b
    d d b b b b b d b b b d b b b b d d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b d d b d b b b b b
    d d b d b b b b d d b d d b b b d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b d d d b b b b b b
    d d b b d d b b d b d d b b b d d b b b b b b b b b b b b b b b b b b b d b b b b b b b b b b b d d d d d b b b b
    d d b b d b b d d b b d d b b b b b b b d b b b b b b b b b b b b b b b b b b b b d b b b b b b b d d b d b b b b
    d d b d b d d d d b b d d b b d d b d b b b d b b b b b b b b b b b b b b b b b b d b d b b b d b d d b b d d b b
    d d b d b b d b b b b b d b b d b d b d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b d b b b b d b
    d b d b b d d d d b d b d d b d b b b b b b b b b d b b b b b b b b b b b b b b d b b b b d b b b b d b b b b b b
    d b d b b d b d b b b b d d b b d b d b b d b b b b b b b b b b b b b b b b b b b b b d b b b b b b b b b b b b b
    d b b b d b d d d b d b d d b d d b d b d b d b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b b
    d b b b b d b d d d b d d d b d d d b d d d d b d d 1 b b b b b b b b b b b b d b d b b b b b b b b b b b b b b b
    d b b b b d b b d d d d d d b b d b d b b d d d d d d b b b b b b b b b b b b d b d b b b b b b b b b b b b b b b
    d b b b b d b b d d d d d d d d d d b b b d d b d d b d d b b b b b b d b b b d b b d b b b b b b b b b b b b b b
    `;